workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
