final demoProducts = [
  {
    'id': 'p1',
    'title': 'Elegant Ethnic Dress 1',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+1',
    'category': 'Ethnic',
  },
  {
    'id': 'p2',
    'title': 'Stylish Western Dress 2',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+2',
    'category': 'Western',
  },
  {
    'id': 'p3',
    'title': 'Elegant Ethnic Dress 3',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+3',
    'category': 'Ethnic',
  },
  {
    'id': 'p4',
    'title': 'Stylish Western Dress 4',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+4',
    'category': 'Western',
  },
  {
    'id': 'p5',
    'title': 'Elegant Ethnic Dress 5',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+5',
    'category': 'Ethnic',
  },
  {
    'id': 'p6',
    'title': 'Stylish Western Dress 6',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+6',
    'category': 'Western',
  },
  {
    'id': 'p7',
    'title': 'Elegant Ethnic Dress 7',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+7',
    'category': 'Ethnic',
  },
  {
    'id': 'p8',
    'title': 'Stylish Western Dress 8',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+8',
    'category': 'Western',
  },
  {
    'id': 'p9',
    'title': 'Elegant Ethnic Dress 9',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+9',
    'category': 'Ethnic',
  },
  {
    'id': 'p10',
    'title': 'Stylish Western Dress 10',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+10',
    'category': 'Western',
  },
  {
    'id': 'p11',
    'title': 'Elegant Ethnic Dress 11',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+11',
    'category': 'Ethnic',
  },
  {
    'id': 'p12',
    'title': 'Stylish Western Dress 12',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+12',
    'category': 'Western',
  },
  {
    'id': 'p13',
    'title': 'Elegant Ethnic Dress 13',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+13',
    'category': 'Ethnic',
  },
  {
    'id': 'p14',
    'title': 'Stylish Western Dress 14',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+14',
    'category': 'Western',
  },
  {
    'id': 'p15',
    'title': 'Elegant Ethnic Dress 15',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+15',
    'category': 'Ethnic',
  },
  {
    'id': 'p16',
    'title': 'Stylish Western Dress 16',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+16',
    'category': 'Western',
  },
  {
    'id': 'p17',
    'title': 'Elegant Ethnic Dress 17',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+17',
    'category': 'Ethnic',
  },
  {
    'id': 'p18',
    'title': 'Stylish Western Dress 18',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+18',
    'category': 'Western',
  },
  {
    'id': 'p19',
    'title': 'Elegant Ethnic Dress 19',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+19',
    'category': 'Ethnic',
  },
  {
    'id': 'p20',
    'title': 'Stylish Western Dress 20',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+20',
    'category': 'Western',
  },
  {
    'id': 'p21',
    'title': 'Elegant Ethnic Dress 21',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+21',
    'category': 'Ethnic',
  },
  {
    'id': 'p22',
    'title': 'Stylish Western Dress 22',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+22',
    'category': 'Western',
  },
  {
    'id': 'p23',
    'title': 'Elegant Ethnic Dress 23',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+23',
    'category': 'Ethnic',
  },
  {
    'id': 'p24',
    'title': 'Stylish Western Dress 24',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+24',
    'category': 'Western',
  },
  {
    'id': 'p25',
    'title': 'Elegant Ethnic Dress 25',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+25',
    'category': 'Ethnic',
  },
  {
    'id': 'p26',
    'title': 'Stylish Western Dress 26',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+26',
    'category': 'Western',
  },
  {
    'id': 'p27',
    'title': 'Elegant Ethnic Dress 27',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+27',
    'category': 'Ethnic',
  },
  {
    'id': 'p28',
    'title': 'Stylish Western Dress 28',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+28',
    'category': 'Western',
  },
  {
    'id': 'p29',
    'title': 'Elegant Ethnic Dress 29',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+29',
    'category': 'Ethnic',
  },
  {
    'id': 'p30',
    'title': 'Stylish Western Dress 30',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+30',
    'category': 'Western',
  },
  {
    'id': 'p31',
    'title': 'Elegant Ethnic Dress 31',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+31',
    'category': 'Ethnic',
  },
  {
    'id': 'p32',
    'title': 'Stylish Western Dress 32',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+32',
    'category': 'Western',
  },
  {
    'id': 'p33',
    'title': 'Elegant Ethnic Dress 33',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+33',
    'category': 'Ethnic',
  },
  {
    'id': 'p34',
    'title': 'Stylish Western Dress 34',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+34',
    'category': 'Western',
  },
  {
    'id': 'p35',
    'title': 'Elegant Ethnic Dress 35',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+35',
    'category': 'Ethnic',
  },
  {
    'id': 'p36',
    'title': 'Stylish Western Dress 36',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+36',
    'category': 'Western',
  },
  {
    'id': 'p37',
    'title': 'Elegant Ethnic Dress 37',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+37',
    'category': 'Ethnic',
  },
  {
    'id': 'p38',
    'title': 'Stylish Western Dress 38',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+38',
    'category': 'Western',
  },
  {
    'id': 'p39',
    'title': 'Elegant Ethnic Dress 39',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+39',
    'category': 'Ethnic',
  },
  {
    'id': 'p40',
    'title': 'Stylish Western Dress 40',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+40',
    'category': 'Western',
  },
  {
    'id': 'p41',
    'title': 'Elegant Ethnic Dress 41',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+41',
    'category': 'Ethnic',
  },
  {
    'id': 'p42',
    'title': 'Stylish Western Dress 42',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+42',
    'category': 'Western',
  },
  {
    'id': 'p43',
    'title': 'Elegant Ethnic Dress 43',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+43',
    'category': 'Ethnic',
  },
  {
    'id': 'p44',
    'title': 'Stylish Western Dress 44',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+44',
    'category': 'Western',
  },
  {
    'id': 'p45',
    'title': 'Elegant Ethnic Dress 45',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+45',
    'category': 'Ethnic',
  },
  {
    'id': 'p46',
    'title': 'Stylish Western Dress 46',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+46',
    'category': 'Western',
  },
  {
    'id': 'p47',
    'title': 'Elegant Ethnic Dress 47',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+47',
    'category': 'Ethnic',
  },
  {
    'id': 'p48',
    'title': 'Stylish Western Dress 48',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+48',
    'category': 'Western',
  },
  {
    'id': 'p49',
    'title': 'Elegant Ethnic Dress 49',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+49',
    'category': 'Ethnic',
  },
  {
    'id': 'p50',
    'title': 'Stylish Western Dress 50',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+50',
    'category': 'Western',
  },
  {
    'id': 'p51',
    'title': 'Elegant Ethnic Dress 51',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+51',
    'category': 'Ethnic',
  },
  {
    'id': 'p52',
    'title': 'Stylish Western Dress 52',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+52',
    'category': 'Western',
  },
  {
    'id': 'p53',
    'title': 'Elegant Ethnic Dress 53',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+53',
    'category': 'Ethnic',
  },
  {
    'id': 'p54',
    'title': 'Stylish Western Dress 54',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+54',
    'category': 'Western',
  },
  {
    'id': 'p55',
    'title': 'Elegant Ethnic Dress 55',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+55',
    'category': 'Ethnic',
  },
  {
    'id': 'p56',
    'title': 'Stylish Western Dress 56',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+56',
    'category': 'Western',
  },
  {
    'id': 'p57',
    'title': 'Elegant Ethnic Dress 57',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+57',
    'category': 'Ethnic',
  },
  {
    'id': 'p58',
    'title': 'Stylish Western Dress 58',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+58',
    'category': 'Western',
  },
  {
    'id': 'p59',
    'title': 'Elegant Ethnic Dress 59',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+59',
    'category': 'Ethnic',
  },
  {
    'id': 'p60',
    'title': 'Stylish Western Dress 60',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+60',
    'category': 'Western',
  },
  {
    'id': 'p61',
    'title': 'Elegant Ethnic Dress 61',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+61',
    'category': 'Ethnic',
  },
  {
    'id': 'p62',
    'title': 'Stylish Western Dress 62',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+62',
    'category': 'Western',
  },
  {
    'id': 'p63',
    'title': 'Elegant Ethnic Dress 63',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+63',
    'category': 'Ethnic',
  },
  {
    'id': 'p64',
    'title': 'Stylish Western Dress 64',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+64',
    'category': 'Western',
  },
  {
    'id': 'p65',
    'title': 'Elegant Ethnic Dress 65',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+65',
    'category': 'Ethnic',
  },
  {
    'id': 'p66',
    'title': 'Stylish Western Dress 66',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+66',
    'category': 'Western',
  },
  {
    'id': 'p67',
    'title': 'Elegant Ethnic Dress 67',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+67',
    'category': 'Ethnic',
  },
  {
    'id': 'p68',
    'title': 'Stylish Western Dress 68',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+68',
    'category': 'Western',
  },
  {
    'id': 'p69',
    'title': 'Elegant Ethnic Dress 69',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+69',
    'category': 'Ethnic',
  },
  {
    'id': 'p70',
    'title': 'Stylish Western Dress 70',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+70',
    'category': 'Western',
  },
  {
    'id': 'p71',
    'title': 'Elegant Ethnic Dress 71',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+71',
    'category': 'Ethnic',
  },
  {
    'id': 'p72',
    'title': 'Stylish Western Dress 72',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+72',
    'category': 'Western',
  },
  {
    'id': 'p73',
    'title': 'Elegant Ethnic Dress 73',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+73',
    'category': 'Ethnic',
  },
  {
    'id': 'p74',
    'title': 'Stylish Western Dress 74',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+74',
    'category': 'Western',
  },
  {
    'id': 'p75',
    'title': 'Elegant Ethnic Dress 75',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+75',
    'category': 'Ethnic',
  },
  {
    'id': 'p76',
    'title': 'Stylish Western Dress 76',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+76',
    'category': 'Western',
  },
  {
    'id': 'p77',
    'title': 'Elegant Ethnic Dress 77',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+77',
    'category': 'Ethnic',
  },
  {
    'id': 'p78',
    'title': 'Stylish Western Dress 78',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+78',
    'category': 'Western',
  },
  {
    'id': 'p79',
    'title': 'Elegant Ethnic Dress 79',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+79',
    'category': 'Ethnic',
  },
  {
    'id': 'p80',
    'title': 'Stylish Western Dress 80',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+80',
    'category': 'Western',
  },
  {
    'id': 'p81',
    'title': 'Elegant Ethnic Dress 81',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+81',
    'category': 'Ethnic',
  },
  {
    'id': 'p82',
    'title': 'Stylish Western Dress 82',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+82',
    'category': 'Western',
  },
  {
    'id': 'p83',
    'title': 'Elegant Ethnic Dress 83',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+83',
    'category': 'Ethnic',
  },
  {
    'id': 'p84',
    'title': 'Stylish Western Dress 84',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+84',
    'category': 'Western',
  },
  {
    'id': 'p85',
    'title': 'Elegant Ethnic Dress 85',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+85',
    'category': 'Ethnic',
  },
  {
    'id': 'p86',
    'title': 'Stylish Western Dress 86',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+86',
    'category': 'Western',
  },
  {
    'id': 'p87',
    'title': 'Elegant Ethnic Dress 87',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+87',
    'category': 'Ethnic',
  },
  {
    'id': 'p88',
    'title': 'Stylish Western Dress 88',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+88',
    'category': 'Western',
  },
  {
    'id': 'p89',
    'title': 'Elegant Ethnic Dress 89',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+89',
    'category': 'Ethnic',
  },
  {
    'id': 'p90',
    'title': 'Stylish Western Dress 90',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+90',
    'category': 'Western',
  },
  {
    'id': 'p91',
    'title': 'Elegant Ethnic Dress 91',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+91',
    'category': 'Ethnic',
  },
  {
    'id': 'p92',
    'title': 'Stylish Western Dress 92',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+92',
    'category': 'Western',
  },
  {
    'id': 'p93',
    'title': 'Elegant Ethnic Dress 93',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+93',
    'category': 'Ethnic',
  },
  {
    'id': 'p94',
    'title': 'Stylish Western Dress 94',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 949,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+94',
    'category': 'Western',
  },
  {
    'id': 'p95',
    'title': 'Elegant Ethnic Dress 95',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 999,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+95',
    'category': 'Ethnic',
  },
  {
    'id': 'p96',
    'title': 'Stylish Western Dress 96',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 1049,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+96',
    'category': 'Western',
  },
  {
    'id': 'p97',
    'title': 'Elegant Ethnic Dress 97',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 1099,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+97',
    'category': 'Ethnic',
  },
  {
    'id': 'p98',
    'title': 'Stylish Western Dress 98',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 799,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+98',
    'category': 'Western',
  },
  {
    'id': 'p99',
    'title': 'Elegant Ethnic Dress 99',
    'description': 'Beautiful ethnic wear, ideal for occasions.',
    'price': 849,
    'image': 'https://placehold.co/600x800?text=Elegant+Ethnic+Dress+99',
    'category': 'Ethnic',
  },
  {
    'id': 'p100',
    'title': 'Stylish Western Dress 100',
    'description': 'Beautiful western wear, ideal for occasions.',
    'price': 899,
    'image': 'https://placehold.co/600x800?text=Stylish+Western+Dress+100',
    'category': 'Western',
  },
];
