name: yash_fashion_hub
description: Yash Fashion Hub - demo prototype
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  fake_async: ^1.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  leak_tracker: ^11.0.1
  leak_tracker_testing: ^3.0.2
  matcher: ^0.12.16+1
  material_color_utilities: ^0.8.0
  meta: ^1.11.0
  nested: ^1.0.0
  path: ^1.8.3
  provider: ^6.1.1
  sky_engine: ^0.0.99
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  string_scanner: ^1.2.0
  term_glyph: ^1.2.1
  test_api: ^0.6.1
  vector_math: ^2.1.4
  vm_service: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo.png
